env                = "dev"
region             = "us-east-1"
aws_account_number = "332281781429"
created_by         = "BizCloudExperts"
application        = "omni-wt-cw-integration"
s3_prefix          = "CargoWiseOutbound/Lenovo"
s3_suffix          = ".xml"
cw_api_endpoint    = "https://trxts3services.wisegrid.net/eAdaptor"
cw_api_auth        = "Basic dHJ4dHMzOjY0ODg1Nw=="
cw_webtracker_base_url = "http://trxts3.webtracker.wisegrid.net/Login/Login.aspx"