env                = "dev"
region             = "us-east-1"
aws_account_number = "332281781429"
created_by         = "BizCloudExperts"
application        = "omni-wt-cw-integration"
s3_prefix          = "CargoWiseOutbound/Lenovo"
s3_suffix          = "xml"
