env                = "prod"
region             = "us-east-1"
aws_account_number = "332281781429"
created_by         = "BizCloudExperts"
application        = "lenovo-integration"
s3_prefix          = "CargoWiseOutbound/Lenovo"
s3_suffix          = "xml"
cw_webtracker_base_url = "https://trxelpwebtracker.wisegrid.net/Login/Login.aspx"
